---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: ninit

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: ninit
rules:
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - events
    verbs:
      - get

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: ninit
subjects:
  - kind: ServiceAccount
    name: ninit
roleRef:
  kind: Role
  name: ninit
  apiGroup: rbac.authorization.k8s.io
