package version

import (
	_ "embed"
	"os"
	"path/filepath"
	"strings"
)

var (
	//go:embed .autogenerated/version
	version string
	//go:embed .autogenerated/buildTime
	buildTime string
)

func dataOrUnknown(v string) string {
	v = strings.TrimSpace(v)

	if v == "" {
		return "UNKNOWN"
	}

	return v
}

// GetVersion returns embedded version info.
func GetVersion() string {
	return dataOrUnknown(version)
}

// GetVersion returns embedded build time.
func GetBuildTime() string {
	return dataOrUnknown(buildTime)
}

// GetApplicationName just a conviniece wrapper
// to get running application base name.
func GetApplicationName() string {
	return filepath.Base(os.Args[0])
}
